### ISSUE TITLE
Не добавляются сенсоры

### ISSUE THREAD

**Issue by Jony26** [dmitry-k/yandex_smart_home#123]
Доброго дня! Не добавляются сенсоры в алису. Кнопки, термостат, освещение - без проблем добавилось.
Уже пробовал насильно прописывать, результата нет. Подскажите как победить?
```
yandex_smart_home:
  filter:
    include_entities:
      - sensor.1_temperature
      - sensor.1_humidity
  entity_config:
    sensor.temp1:
      name: Датчик на кухне
      room: кухня
      properties:
        - type: temperature
          entity: sensor.1_temperature
        - type: humidity
          entity: sensor.1_humidity
```

**Comment by Zuz666** [comment]
Как-то так:
```yaml
yandex_smart_home:
  filter:
    include_entities:
      - sensor.1_temperature
  entity_config:
    sensor.1_temperature:
      name: Датчик на кухне
      room: кухня
      properties:
        - type: humidity
          entity: sensor.1_humidity
```

**Comment by Jony26** [comment]
Разобрался.
Заходят но по одному параметру
`    sensor.1_temperature:
      name: Датчик температуры
      room: кухня
      properties:
        - type: temperature
          entity: sensor.1_temperature`

**Comment by Zuz666** [comment]
> Заходят но по одному параметру

Нет не разобрались, если нужно просто по одному парметру, то достаточно так:

```yaml
yandex_smart_home:
  filter:
    include_entities:
      - sensor.1_temperature
```

Если хотите скомбинировать, то я выше показал как это сделать (именно так сейчас работает).

Тут https://github.com/dmitry-k/yandex_smart_home/issues/118 об это рассказано.

**Comment by Jony26** [comment]
Спасибо! Действительно сегодня завелось без проблем. Вчера по такому коду "ошибка обновления".
```
    sensor.1_temperature:
      name: Датчик на кухне
      room: кухня
      properties:
        - type: temperature
          entity: sensor.1_temperature
        - type: humidity
          entity: sensor.1_humidity   
```
У меня если датчик не объявлен в properties: то в алисе не виден...
