### ISSUE TITLE
Полные данные робота Алисе

### ISSUE THREAD

**Issue by lexural** [dmitry-k/yandex_smart_home#132]
Пропбосил к Алисе робота Xiaomi Mijia 1S
Робот описан как:
```
vacuum:
  - platform: xiaomi_miio
    name: 'Vacuum 1S'
    host: 192.168.1.49
    token: 6f496442716f6750412345586a554547
    device_id: vacuum_1s
```

Что ещё дописать, что бы Алиса увидела все данные робота? А именно:
```
Производитель: roborock
Модель устройства: roborock.vacuum.m1s
Версия ПО: 3.5.4_0948
```

А то она чуть не верно стала команду "Отправь на базу" выполнять. Ставит на паузу. Если же через шлюз сяоми пробрасывать, то всё ОК.
