### ISSUE TITLE
Не получается добавить сенсор с параметрами

### ISSUE THREAD

**Issue by GodinRaider** [dmitry-k/yandex_smart_home#158]
Не прокидывается сенсор, если к нему указать еще несколько других сенсоров в параметрах.
Как отдельные устройства можно добавить.
```
yandex_smart_home:
  filter:
    include_entities:
      - switch.godin_pc
      - sensor.0x158d0001b7b252_temperature
      - sensor.0x158d0001b7b252_humidity
      - sensor.0x158d0001b7b252_pressure
      - binary_sensor.0x158d0001de771d_contact
      - binary_sensor.0x158d000411410b_motion
      - light.sonoff_1000b3e98b
  entity_config:
    sensor.0x158d0001b7b252_temperature:
        type: devices.types.sensor
        properties:
            - type: temperature
              entity: sensor.0x158d0001b7b252_temperature
            - type: humidity
              entity: sensor.0x158d0001b7b252_humidity
            - type: pressure
              entity: sensor.0x158d0001b7b252_pressure
```
В данном конфиге пробросилось все, кроме сенсора температуры (в который я добавил параметрами влажность и давление). Если закомментировать для этого сенсора entity_config, то как отдельное устройство датчик температуры добавляется.

**Comment by Bratan9600** [comment]
Кажется проблема в том, что пытаетесь пробросить сущность с одним и тем же ID: сущность sensor.0x158d0001b7b252_temperature у вас определена самим хассом и вы ее включили в  include_entities: . 
В данном случае попробуйте переименовать сущность в entity_config: например вот так:
`
  entity_config:
    sensor.mymicroclimate:
        type: devices.types.sensor
        properties:
            - type: temperature
              entity: sensor.0x158d0001b7b252_temperature
            - type: humidity
              entity: sensor.0x158d0001b7b252_humidity
            - type: pressure
              entity: sensor.0x158d0001b7b252_pressure`

**Comment by GodinRaider** [comment]
Я верно понимаю, что нужно использовать как "основу" просто какой-то другой сенсор (который и не нужен в УДЯ), а уже в него накидать нужных?

**Comment by Bratan9600** [comment]
> Я верно понимаю, что нужно использовать как "основу" просто какой-то другой сенсор (который и не нужен в УДЯ), а уже в него накидать нужных?

Как вариант.
Еще можно попробовать убрать из     include_entities: сам сенсор температуры.

**Comment by GodinRaider** [comment]
> Как вариант.
> Еще можно попробовать убрать из include_entities: сам сенсор температуры.

Ну раньше точно у меня было так: если убрать сам сенсор температуры из include_entities, то он и не отображался.
Спасибо, сейчас попробую разные варианты.

**Comment by GodinRaider** [comment]
К сожалению, ни добавление "левого" сенсора как "основу", ни удаление из include_entities самого сенсора температуры, если прокидывается именно он, не помогли.
Просто не добавляется такое устройство.
И почему то только сенсор.
Добавил только что лампочку, куда прописал внутрь датчик температуры - и работает: лампочка, со "встроенным" градусником.

**Comment by Bratan9600** [comment]
> К сожалению, ни добавление "левого" сенсора как "основу", ни удаление из include_entities самого сенсора температуры, если прокидывается именно он, не помогли.
> Просто не добавляется такое устройство.
> И почему то только сенсор (любой, пробовал другие сенсоры с include_entities делать - точно также).
> Добавил только что лампочку, куда прописал внутрь датчик температуры - и работает: лампочка, со "встроенным" градусником.

Видимо все же не работает. Проверил сейчас у себя. Тоже не добавляет сенсор, если ему в свойствах указать тоже сенсор.

**Comment by akarpych** [comment]
У меня тоже не добавляется через properties.
Добавился только как отдельное устройство...

**Comment by Zuz666** [comment]
@GodinRaider, @akarpych вы используете последний мастер? Если да, то уберите всё что с pressure связано и заработает. Там проблема в есть в обработке в CustomEntityProperty, подробнее [тут](https://github.com/dmitry-k/yandex_smart_home/pull/155#issuecomment-798995269): 

Пример, работающего конфига:
```yaml
yandex_smart_home:
  filter:
    include_entities:
      # sensors
      - sensor.0x158d0004657cb8_temperature
      - sensor.home_air_quality_co2_level
  entity_config:
    # sensors
    sensor.0x158d0004657cb8_temperature:
      name: Датчик климата в спальне
      room: Спальня
      properties:
# Это НЕ нужно добавляется автоматически
#        - type: temperature
#          entity: sensor.0x158d0004657cb8_temperature
        - type: humidity
          entity: sensor.0x158d0004657cb8_humidity
        - type: pressure
          entity: sensor.0x158d0004657cb8_pressure
    sensor.home_air_quality_co2_level:
      name: Датчик воздуха в кабинете
      room: Кабинет
      properties:
        - type: temperature
          entity: sensor.home_air_quality_temperature
        - type: humidity
          entity: sensor.home_air_quality_humidity
# Это нужно НЕ добавляется автоматически
        - type: co2_level
          entity: sensor.home_air_quality_co2_level
```

На вкладке тестирования диалога можно увидеть все ошибки, добавление рекомендую проводить от туда же, там вижно что запрошено и что пришло в ответ.
