### ISSUE TITLE
Кондиционер: скорости обдува в Алисе не совпадают с исходной

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#173]
Мой компонент климат в homeassistant имеет следующую конфигурацию:
    fan_modes:
      **- "min"
      - "mid"
      - "max"
      - "auto"**
Однако в Яндексе режимы передаются следующие:
**Авто
Низкая
Турбо**

Вот скрин: https://prntscr.com/11j8t1p
 Это возможно исправить? 

Режим термостата и температура передаются правильно.
На всякий случай, вот мой полный конфиг: 
```
  - platform: mqtt
    name: haier
    modes:
      - "off"
      - "cool"
      - "heat"
      - "auto"
      - "fan_only"
      - "dry"
    fan_modes:
      - "min"
      - "mid"
      - "max"
      - "auto"
    swing_modes:
      - "ud"
      - "lr"
      - "all"
      - "off"
    max_temp: 30
    min_temp: 16
    precision: 1.0
    retain: true
    power_command_topic: "myhome/topic/set/Power"
    mode_command_topic: "myhome/topic/set/Mode"
    mode_state_topic: "myhome/topic/Mode"
    temperature_command_topic: "myhome/topic/set/Set_Temp"
    temperature_state_topic: "myhome/topic/Set_Temp"
    fan_mode_command_topic: "myhome/topic/set/Fan_Speed"
    fan_mode_state_topic: "myhome/topic/Fan_Speed"
    swing_mode_command_topic: "myhome/topic/set/Swing"
    swing_mode_state_topic: "myhome/topic/Swing"
    current_temperature_topic: "myhome/topic/Current_Temp"
```
