### ISSUE TITLE
Статус "удобрения - conductivity" для запроса статуса сенсора Mi Flora

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#176]
У меня в HA установлен компонент plants (mi_flora от xiaomi):
```
plants:
  dracena:
    sensors:
      moisture: sensor.dratsena_moisture
      battery: sensor.dratsena_battery
      temperature: sensor.dratsena_temperature
      conductivity: sensor.dratsena_conductivity
      brightness: sensor.dratsena_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 32
    min_brightness: 1500
    max_brightness: 6000
```
В Яндекс я смог прокинуть температуру, влажность, уровень батарейки, и объединить их в один датчик, вот код:
```
  filter:
    exclude_entities:
      - sensor.dratsena_moisture
    include_entities:
      - sensor.dratsena_temperature
  entity_config: 
    sensor.dratsena_temperature:
      name: Драцена
      room: Гостиная
      properties:
      - type: temperature
        entity: sensor.dratsena_temperature
      - type: humidity
        entity: sensor.dratsena_moisture
      - type: battery_level
        entity: sensor.dratsena_battery
```
Подскажите, можно ли прокинуть статусы "удобрения" ?
Я пробовал добавлять так:
```
   entity_config: 
    sensor.dratsena_temperature:
      name: Драцена
      room: Гостиная
      properties:
      - type: conductivity
        sensor.dratsena_conductivity

```
Но это не работает, яндекс перестает обновлять устройства и выдает ошибку.
