### ISSUE TITLE
Термостат, не могу пробросить   away_temp (preset_mode: away)

### ISSUE THREAD

**Issue by gumileeev** [dmitry-k/yandex_smart_home#190]
Не могу добавить кнопку режима отсутствия* (10 градусов) в яндекс, что я делаю не так? 
Настройка термостата в yandex_smart_home:
```
  entity_config:
    climate.prihojaya:
      name: "Обогреватель"
      modes:
        thermostat:
          heat: [heat]
          cool: [away]
```
Настройка термостата в ХА:
```
  - platform: generic_thermostat
    name: prihojaya
    unique_id: prihojaya
    heater: switch.sonoff_10007bea19
    target_sensor: sensor.temperature_purifier_prihojaya
    min_temp: 5
    max_temp: 27
    target_temp: 23.5
    cold_tolerance: 1
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 1
    away_temp: 10
    precision: 0.1
```
Скрин устройства в Яндекс: 
![image](https://user-images.githubusercontent.com/39103834/115632075-aa2f5e00-a30f-11eb-8287-9de493607bfe.png)
Скрин пресета из ХА:
![image](https://user-images.githubusercontent.com/39103834/115632267-04302380-a310-11eb-9bba-68ce848f6633.png)
