### ISSUE TITLE
Добавление бризера Xiomi

### ISSUE THREAD

**Issue by MGlants** [dmitry-k/yandex_smart_home#212]
Привет, пытаюсь добавить бризер Xiomi с fan_modes
вот так его видит HA:
```
preset_modes:
  - Auto
  - Silent
  - Interval
  - Low
  - Middle
  - Strong
preset_mode: Middle
model: zhimi.airfresh.va4
temperature: 20.2
aqi: 58
average_aqi: 4
co2: 555
humidity: 74
mode: middle
led: false
led_brightness: 2
buzzer: true
child_lock: false
filter_life_remaining: null
filter_hours_used: 1077
use_time: 3878100
motor_speed: 797
extra_features: null
ptc: false
friendly_name: Bedroom_Ventilation
supported_features: 8

```
Настройка для Яндекса выглядит следующим образом:
```
fan.bedroom_ventilation:
      name: Бризер в спальне
      room: Спальня
      type: devices.types.purifier
      modes:
        fan_speed:
          auto: [auto]
          low: [low]
          medium: [middle]
          high: [strong]
          quiet: [silent]
```

Однако яндекс получает только 
`"payload": {"devices": [{"id": "fan.bedroom_ventilation", "capabilities": [{"type": "devices.capabilities.on_off", "state": {"instance": "on", "value": true}}], "properties": []}]}
`

В HA добавлен следующим образом
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: Bedroom_Ventilation
    host: #hidden#
    token: #hidden#
    model: zhimi.airfresh.va4
```

Судя по всему интеграция с Xiomi не поддерживает fan_speed, но поддерживает preset_mode.
Можно ли сделать маппинг одного к другому?
