### ISSUE TITLE
Не добавляется одноканальный диммер Lonsonho

### ISSUE THREAD

**Issue by cpsskipper** [dmitry-k/yandex_smart_home#245]
Одноканальный диммер Lonsonho TS110F не добавляется в Yandex. При этом аналогичный двухканальный диммер добавился. Проверено на двух одноканальных и двух двухканальных.

Настройки yandex_smart_home

```
yandex_smart_home:
  filter:
    include_entities:
# `Свет спальня, одноканальный диммер
      - light.0x60a423fffe800bd7
# Свет в кухне, двухканальный диммер, канал 2
      - light.0x60a423fffe800a48_l2
# Свет торшер, двухканальный диммер, канал 1
      - light.0x60a423fffe800a48_l1
# Свет туалет, двухканальный диммер канал 2
      - light.0x842e14fffe19ebf8_l2
# Свет ванная, двухканальный диммер канал 1
      - light.0x842e14fffe19ebf8_l1
     
  entity_config:
    light.0x60a423fffe800d47:
      name: Свет
      room: Коридор    
    light.0x60a423fffe800bd7:
      name: Свет
      room: Спальня        
    light.0x60a423fffe800a48_l2:
      name: Свет
      room: Кухня 
    light.0x60a423fffe800a48_l1:
      name: Торшер
      room: Кухня 
    light.0x842e14fffe19ebf8_l2:
      name: Свет
      room: Туалет 
    light.0x842e14fffe19ebf8_l1:
      name: Свет
      room: Ванная 
```
