### ISSUE TITLE
После установки последнего обновления снова нет кондиционера.

### ISSUE THREAD

**Issue by AntoxaSa** [dmitry-k/yandex_smart_home#258]
Дмитрий день добрый!
Установил последнее обновление. У кондиционера отказали режим авто.Потом удалил кондиционер из списка устройств.Сделал обновить список кондиционера нет  больше.

**Comment by dext0r** [comment]
Покажите атрибуты кондиционера из Developers Tools -> States и конфигурацию из entity_config (если есть)

**Comment by AntoxaSa** [comment]
Вот атрибуты: 
hvac_modes: auto, off, cool, heat, dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes: AUTO, 1, 2, 3, 4
swing_modes: AUTO, 1, 2, 3, 4, 5, SWING
current_temperature: 25
temperature: 22
fan_mode: 1
swing_mode: AUTO
friendly_name: hvac_lr
supported_features: 41

**Comment by AntoxaSa** [comment]
Просто прописано:
   include_domains:
     - climate
    в entity config ничего нет по кондиционеру

**Comment by dext0r** [comment]
А что это за кондиционер и какой интеграцией он управляется?

**Comment by AntoxaSa** [comment]
просто через MQTT.
climate.hvac_lr
кондиционер митсубиши электрик проброшен через ESP

**Comment by AntoxaSa** [comment]
befdec4
Установленная версия
Восстанавливаю из бекапа эту версию все работает

**Comment by dext0r** [comment]
> hvac_modes: auto, off, cool, heat, dry
`auto` - не совсем корректно использовать, потому что это "The device is set to a schedule, learned behavior, AI."
Вместо `auto` должно быть `heat_cool`. Собственно об этом писали в #252.

Чтобы все починить вам нужно выбрать из двух вариантов:
1. Использовать heat_cool вместо auto в hvac_modes
2. Добавить в конфигурацию yandex_home:
```yaml
entity_config:
  climate.hvac_lr:
    modes:
      auto: [auto]
      cool: [cool]
      heat: [heat]
      dry: [dry]
```

**Comment by AntoxaSa** [comment]
не совсем понял, как мне его использовать? Использовать heat_cool вместо auto в hvac_modes

**Comment by AntoxaSa** [comment]
![IMG_4618](https://user-images.githubusercontent.com/71827946/127028311-90cf8f49-5026-4e79-ba8e-06b23879063c.jpg)
Попробовал по второму варианту ошибку выкидывает по 132 строке, что не так делаю?

**Comment by AntoxaSa** [comment]
Сделал вот так в конфиге:
 entity_config: 
    
    light.nastolnaia_lampa:
      name: "Настольная лампа"
      room: "Комната"
    climate.hvac_lr: 
      name: "Кондиционер"
      room: "Комната"
      modes:
       hvac_modes:
        auto: [auto]
        cool: [cool]
        heat: [heat]
        off: [off]
        dry: [dry]
кондиционера так и не видит яндекс при добавлении устройства

**Comment by dext0r** [comment]
Извиняюсь, неправильно написал. Вот верный вариант:
```
climate.hvac_lr: 
  name: "Кондиционер"
  room: "Комната"
  modes:
    thermostat:
      auto: [auto]
      cool: [cool]
      heat: [heat]
      dry: [dry]
```
`off` не нужен

**Comment by AntoxaSa** [comment]
Применил данный конфиг,ошибок нет.Но яндекс так же не видит устройство.

**Comment by AntoxaSa** [comment]
2021-07-27 08:35:27 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Notify Yandex about new state media_player.yandex_station_ff98f029b3bab4f30a965b06: idle
2021-07-27 08:35:27 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Request: https://dialogs.yandex.net/api/v1/skills/34e40237-5b6e-44d5-8b47-f68b99df2c2b/callback/state (POST data: {'ts': 1627356927.5344255, 'payload': {'user_id': 'ecf70f2ac45a488782558bb3a7b75ce3', 'devices': [{'id': 'media_player.yandex_station_ff98f029b3bab4f30a965b06', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}, {'type': 'devices.capabilities.toggle', 'state': {'instance': 'mute', 'value': False}}, {'type': 'devices.capabilities.toggle', 'state': {'instance': 'pause', 'value': True}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'volume', 'value': 100}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'channel', 'value': 0}}], 'properties': []}]}})
[лог.txt](https://github.com/dmitry-k/yandex_smart_home/files/6882514/default.txt)

**Comment by AntoxaSa** [comment]
вот часть лога и файл лог.txt может что то поможет понять проблему

**Comment by dext0r** [comment]
По логу вижу две проблемы:
1. auto по прежнему не отдается, похоже что-то не так сделано в entity_config.
2. Кондей умеет swing, но его режимы не удалось связать с яндексом, поэтому Яндекс не хочет добавлять устройство. 

Обновлённый entity_config:
```yaml
climate.hvac_lr: 
  name: "Кондиционер"
  room: "Комната"
  modes:
    thermostat:
      auto: [auto]
      cool: [cool]
      heat: [heat]
      dry: [dry]
   swing:
      both: [SWING]
      stationary: [AUTO]
      vertical: ['1']
      horizontal: ['2']
```

По swing: нужно будет подставить ваши актуальные значения, я не знаю что делают режимы 1, 2, 3, 4.
Просьба показать скриншот финального конфига для проверки.

p.s. у нас есть чатик https://t.me/yandex_smart_home, туда можно писать для получения более оперативной поддержки :)
