### ISSUE TITLE
Не получается сделать блок notifier, что не так?

### ISSUE THREAD

**Issue by ikey-ru** [dmitry-k/yandex_smart_home#289]
Подскажите пожалуйста, что не так в конфиге, получаю при проверке Invalid config for [yandex_smart_home]: expected a dictionary for dictionary value @ data['yandex_smart_home']['notifier']. Got [OrderedDict([('oauth_token', 'AQAAAA....

Пример
```
yandex_smart_home:
  notifier:
    - oauth_token: AQAAAAAA7SyfAAT7o9uq4MEaVUzHdnqzLSiCThI
      skill_id: 00da726f-a884-4814-9b6d-03b0c7ca2fe3
      user_id: 0968c2b3e0ee4a1ea0cabb0b742186d7

  filter:
    include_entities:
      switch.0xfefefefefefefefe_l8:
        name: Сигналка
        room: Девятый
      switch.0x00124b002252afcd_l8:
        name: Свет желтый
        room: Девятый
        type: device-type-light
```
