### ISSUE TITLE
Пользовательские умения - чайник Redmond. Как все запихнуть в одно устройство?

### ISSUE THREAD

**Issue by DivanX10** [dmitry-k/yandex_smart_home#291]
С появлением возможности использовать пользовательские умения я решил переделать управление чайником. Ниже 3 варианта кода. Первый вариант работает отлично, но хотелось бы, чтобы все это было в одном устройстве. Остальные два варианта позволяют запихнуть все в одно устройство, но не работает подсветка чайника. Говорю включи подсветку чайника, но вместо подсветки чайника включается сам чайник. Можно, конечно, к примеру в Home Assistnat использовать вспомогательный элемент "переключатель" и сделать автоматику и это будет работать.  В документации Яндекс пишется, что можно использовать [devices.types.light в сustom_toggles](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/toggle-instance.html#toggle-instance__backlight) . Во втором варианте я использовал  custom_toggles и backlight и почему-то это не работает. Может я что-то не так делаю. Как правильно сделать?

**Вариант 1: Если я использую такой код, то в ЯУД пробрасывается два чайника**

Что работает?
1) включить\выключить чайник
2) включить\выключить подсветку
3) выставить температуру
4) регулировка яркости подсветки
5) выбор цвета для подсветки
6) отображение текущей температуры

```
    climate.r4s1_kettle_temp:
      name: Чайник
      room: Кухня
      type: devices.types.cooking.kettle
    light.r4s1_kettle_light:
      name: Чайник
      room: Кухня
      type: devices.types.light
```

![image](https://user-images.githubusercontent.com/64090632/128748608-ba77c1c2-258b-464a-81cc-4dc3d03e6f2e.png)
![image](https://user-images.githubusercontent.com/64090632/128748651-9dd1fe26-e4bc-4012-8175-d3a7ea5e056f.png)
![image](https://user-images.githubusercontent.com/64090632/128748665-fbff3884-af69-4a3f-8929-f381575442c3.png)

**Вариант 2: Если я использую код, то в ЯУД пробрасывается один чайник, но не включается подсветка**

Что работает?
1) включить\выключить чайник
2) выставить температуру
3) отображение текущей температуры
```
    climate.r4s1_kettle_temp:
      name: Чайник
      room: Кухня
      type: devices.types.cooking.kettle
      custom_toggles:
        backlight:
          state_entity_id: light.r4s1_kettle_light
          turn_on:
            service: light.turn_on
            entity_id: light.r4s1_kettle_light
          turn_off:
            service: light.turn_off
            entity_id: light.r4s1_kettle_light
```

**Вариант 3: Если я использую код, то в ЯУД пробрасывается один чайник, но не включается подсветка**

Что работает?
1) включить\выключить чайник
2) выставить температуру
3) отображение текущей температуры

```
    switch.r4s1_kettle_boil:
      name: Чайник
      room: Кухня
      custom_toggles:
        backlight:
          state_entity_id: light.r4s1_kettle_light
          turn_on:
            service: light.turn_on
            entity_id: light.r4s1_kettle_light
          turn_off:
            service: light.turn_off
            entity_id: light.r4s1_kettle_light
      custom_ranges:
        temperature:
          state_attribute: temperature
          set_value:
            service: climate.set_temperature
            data:
              temperature: '{{ value }}'
            target:
              entity_id: climate.r4s1_kettle_temp
          range:
            min: 40
            max: 90
            precision: 10
      properties:
        - type: temperature
          entity: climate.r4s1_kettle_temp
          attribute: current_temperature
```

**Например кондиционер + пользовательские умения без проблем работают. Добавил кроме основных функции, ионизатор и подсветку**

```
    climate.aс_living_room:
      type: devices.types.thermostat.ac
      name: Кондиционер
      room: Гостиная
      custom_toggles:
        ionization:
          state_entity_id: switch.aс_ionizer
          turn_on:
            service: switch.turn_on
            entity_id: switch.aс_ionizer
          turn_off:
            service: switch.turn_off
            entity_id: switch.aс_ionizer
        backlight:
          state_entity_id: input_boolean.ac_lighting
          turn_on:
            service: input_boolean.turn_on
            entity_id: input_boolean.ac_lighting
          turn_off:
            service: input_boolean.turn_off
            entity_id: input_boolean.ac_lighting
```

![image](https://user-images.githubusercontent.com/64090632/128750468-4d4dcc82-b3ac-4391-ba13-d488a16fdce5.png)
