### ISSUE TITLE
Добавить маппинг swing для DIY кондиционеров на ESP

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#298]
https://blog.instalator.ru/archives/2683
https://4pda.to/forum/index.php?showtopic=1028652

```yaml
yandex_smart_home:
  entity_config:
    climate.XXX:
      modes:
        swing:
          auto: ['all']
          stationary: ['off']
          horizontal: ['lr']
          vertical: ['ud']
```
