### ISSUE TITLE
Добавление/исключение определенных устройства

### ISSUE THREAD

**Issue by tweaker** [dmitry-k/yandex_smart_home#3]
Просьба или пожелание реализовать добавление/исключение определенных устройств , например как в `homkit`:
```yaml
filter:
  include_entities:
    - light.living_room_chandelier
  exclude_entities:
    - light.living_room_lamp
```
А так все работает отлично! Спасибо за компонент!

**Comment by dmitry-k** [comment]
Тут настройки на основе google assistant. Удобство спорное, но решил что будет проще так для тех кто уже пользовался GA.

```yaml
entity_config:
  light.living_room_chandelier
    expose: true
  light.living_room_lamp
    expose: false
```
должно работать аналогично

**Comment by tweaker** [comment]
Ну просто проще мне кажется прописать, что хочу прокинуть в яндекс, или прокинуть все или группу, но исключить некоторое.

**Comment by cacherocks** [comment]
А как все таки сделать, чтобы добавлялись только указанные в конфиге ХА устройства (которые прописал в энтити конфиге)?

**Comment by tweaker** [comment]
> А как все таки сделать, чтобы добавлялись только указанные в конфиге ХА устройства (которые прописал в энтити конфиге)?

Как я понял только путем исключения:
```yaml
exposed_domains:
  - switch
  - light
  - fan
entity_config:

  # Inc
  fan.living_room_fan:
    name: 'Вентилятор'
    room: 'Гостиная'
    expose: True

  # exl
  light.hallway_lamp1:
    expose: False
```
И вот так вот `expose: False` описывал, что нужно исключить из Алисы

**Comment by dmitry-k** [comment]
Должен работать такой вариант:
```yaml
yandex_smart_home:
  exposed_domains:
  entity_config:
    fan.living_room_fan:
      name: 'Вентилятор'
      room: 'Гостиная'
    light.hallway_lamp1:
      name: 'Лампа'
      room: 'Коридор'
```
Если "exposed_domains:" не прописать то включаются дефолтные группы. Поэтому строчку надо добавить, но не заполнять элементы.

Это лучше чем везде "expose: false" прописывать, но тоже недостаточно хорошо.
Я думаю поменять логику на включение дефолтных групп толко в том случае если вручную ничего не выбрано.
И добавить "expose_entities" и "hide_entities". И "rooms" который будет эквивалентом expose_entities, но с разбивкой по комнатам.
Чтобы работал конфиг типа такого:

``` yaml
yandex_smart_home:
  exposed_domains:
    - light
  expose_entities:
    - switch.hallway
  hide_entities:
    - light.hallway_lamp1
  rooms:
    Гостиная:
        - fan.living_room_fan
        - light.highlight
   Коридор:
        - light.hallway_lamp2

```
