### ISSUE TITLE
Не срабатывает фильтр в HA

### ISSUE THREAD

**Issue by zubikovap** [dmitry-k/yandex_smart_home#310]
Получал ошибку.

> Logger: custom_components.yandex_smart_home.smart_home
> Source: custom_components/yandex_smart_home/smart_home.py:47
> Integration: Yandex Smart Home (documentation, issues)
> First occurred: 22:59:00 (4 occurrences)
> Last logged: 23:16:51
> Handler process error: NOT_SUPPORTED_IN_CURRENT_MODE Unsupported value 'discharging' for instance battery_level of sensor.m2004j19c_sostoianie_akkumuliatora

Настроил фильтр.
```
 filter:
    exclude_domains: 
      - binary_sensor
    exclude_entity_globs:
      - script.box_*
      - sensor.m2004j19c_*
      - sensor.realme_*
      - sensor.realme_8_*
```

Но ошибка все равно выходит.
Что делаю не так?
