### ISSUE TITLE
Кондиционеры

### ISSUE THREAD

**Issue by kuneev** [dmitry-k/yandex_smart_home#314]
Добрый день. Подскажите, пожалуйста, есть ли возможность (или появится ли в будущем) прокидывать кондиционеры в Яндекс именно как кондиционеры, а не термостаты?

**Comment by dext0r** [comment]
Для кондиционеров необходимо задать тип вручную через `entity_config`, например:
```yaml
yandex_smart_home:
  entity_config:
    climate.my_ac:
      type: devices.types.thermostat.ac
```

Автоматикой отличить кондиционер от термостата невозможно. В HA нет атрибута, по которому можно это понять.
