### ISSUE TITLE
Unknown error calling yandex_smart_home CONFIG_SCHEMA

### ISSUE THREAD

**Issue by densanx** [dmitry-k/yandex_smart_home#337]
Здравствуйте.
Провел обновление HA с 2021.11.3 на 2021.11.5. Сразу после обновления получил ошибку:
`Unknown error calling yandex_smart_home CONFIG_SCHEMA`
На всякий случай обновил Yandex Smart Home до v0.3.2. Не помогло.
Используется прямое подключение. Конфиг минимальный:
```
сat yandex_smart_home.yaml 
filter:
  include_domains:
#    - media_player
#    - script
#  include_entities:
#    - media_player.tv
#    - media_player.tv_lg
entity_config:
  media_player.tv_lg:
#    channel_set_via_media_content_id: true
```
Последнюю строку закоментировал 1-2 месяца назад, когда при очередном обновлении компонент написал что данная опция уже не поддерживается.

Прошу помощи: как реанимировать работу.
