### ISSUE TITLE
mid скорость для climate

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#347]
```
Logger: custom_components.yandex_smart_home.capability_mode
Source: custom_components/yandex_smart_home/capability_mode.py:111
Integration: Yandex Smart Home (documentation, issues)
First occurred: 11:28:50 (6 occurrences)
Last logged: 12:20:28

Unable to get Yandex mode for "mid" for fan_speed instance of climate.daichi_1. It may cause inconsistencies between Yandex and HA. Check "modes" setting for this entity

- platform: mqtt
    name: daichi_1
    modes:
      - "cool"
      - "heat"
      - "auto"
      - "fan_only"
      - "dry"
      - "off"
    fan_modes:
      - "min"
      - "mid"
      - "max"
      - "auto"
    swing_modes:
      - "ud"
      - "off"
```

https://blog.instalator.ru/archives/433
