### ISSUE TITLE
Не возвращается статус по шторам без поддержки SUPPORT_SET_POSITION

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#349]
Вызвано #236
```
сover:
  - platform: template
    covers:
      gate:
        friendly_name: Gate
        device_class: garage
        value_template: >-
          {{ is_state('binary_sensor.gate_close_sensor_contact', 'off') }}
        open_cover:
          - condition: state
            entity_id: binary_sensor.gate_close_sensor_contact
            state: 'on'
          - service: switch.turn_on
            entity_id: switch.gate_open_relay
        close_cover:
          - condition: state
            entity_id: binary_sensor.gate_close_sensor_contact
            state: 'off'
          - service: switch.turn_on
            entity_id: switch.gate_open_relay
        stop_cover:
          service: switch.turn_on
          entity_id: switch.gate_open_relay
```
