### ISSUE TITLE
Управление ТВ

### ISSUE THREAD

**Issue by 3AXAPOB** [dmitry-k/yandex_smart_home#36]
Добавьте пожалуйста возможность переключение ТВ каналов по номеру канала.

**Comment by tayanov** [comment]
так яндекс и не предаставляет такой функционал. делайте template_swinch на каждый канал.

**Comment by dmitry-k** [comment]
Насколько я понимаю, нет общего решения для этого. В HA нет устройства "телевизор" сервисом для переключения каналов.
Есть несколько устройств "remote" который, вероятно, умеют переключать каналы, но там у каждого свои команды/логика. Нельзя написать общее решение для всех пультов.

Со стороны яндекса тоже можно только канал выше/ниже выбрать, а не конкретный по номеру.

**Comment by 3AXAPOB** [comment]
Канал можно выбрать по номеру, Яндекс такую возможность предоставляет. Вот например реализация в Мажордомо https://kb.mjdm.ru/yandexhome_help/

**Comment by dmitry-k** [comment]
Ok, но со стороны HA это всё ещё проблематично.

smartIR это какой-то нестандартный компонент? Вводить зависимость от него это перебор. А что если у кого-то Xiaomi IR Remote или Harmony Hub?

Тут надо  какую-то гибкую настройку вводить, объединять внутри устройства media_player и remote чтобы они со стороны яндекса выглядели как одно(а в remote надо ещё и разные команды отправлять на переключение каналов в зависимости от компонента).

Если кто-то сделает общее, достаточно красивое решение, то я приму PR. Но это сложная задача. Сам вряд ли буду тратить время на это пока что, сорри.

**Comment by 3AXAPOB** [comment]
Может можно передать номер канала как значение какому-то сенсору а дальше уже пусть пользователь делает автоматизацию? Готов задонатить 1000 руб. реализовавшему эту функцию.

**Comment by ekorsanov01** [comment]
Спасибо за такой крутой проект

Каналы можно переключать в HA через:
```yaml
service: media_player.play_media
      data_template:
         entity_id: 'media_player.living_room_tv'
         media_content_id: "Номер канала"
         media_content_type: "channel"
```
и можно еще менять сорс:
```yaml
    service: media_player.select_source
       data_template:
           entity_id: 'media_player.living_room_tv'
           source: "HDMI-1"
```
было бы очень круто если бы вы добавили такой функционал. 
и еще бы увеличение громкости на какое нибудь число:

**Comment by dmitry-k** [comment]
@ekorsanov01, интересно. Смена каналов таким образом работать будет не везде, но на LG и Samsung должна.
У меня Sony и антенна не подключена, но в документации компонента нет такого способа переключения, видны ошибки в логе и сам телевизор не пытается переключить канал.
Я сделал бранч https://github.com/dmitry-k/yandex_smart_home/tree/tv-channel. Если кто-то с LG или Samsung проверит и подтвердит работоспособность, то наверное включу это в master.

По поводу source: со стороны яндекса ничего подходящего не вижу пока.

По поводу значения громкости: раньше такой возможности не было со стороны яндекса. Сейчас, вроде бы, возможно. Посмотрю позже.

**Comment by ekorsanov01** [comment]
на LG проверил, работает как надо
на Philips не работает (( там немного другой механизм
на нем надо переключать сорс ( 
```yaml
media_player.select_source
   entity_id: media_player.philips_tv
   source: 'Channel: Карусель'
```

но на обоих теликах работает функция

```yaml
media_player.media_next_track
```

и
```yaml
media_player.media_previous_track
```
