### ISSUE TITLE
Включение чайника через сервис water_heater.turn_on

### ISSUE THREAD

**Issue by ClusterM** [dmitry-k/yandex_smart_home#363]
Почему операции "включить" и "выключить" для `water_heater` сделаны через переключение режимов?

https://github.com/dmitry-k/yandex_smart_home/blob/c65ba7ba719cd645a800f879d02ac4aa0399c4df/custom_components/yandex_smart_home/capability_onoff.py#L363
https://github.com/dmitry-k/yandex_smart_home/blob/c65ba7ba719cd645a800f879d02ac4aa0399c4df/custom_components/yandex_smart_home/capability_onoff.py#L373

У меня, например, это режим "boil".

У `water_heater` есть же методы `turn_on` и `turn_off`. И есть соответствующие сервисы для включения и выключения - `water_heater.turn_on` и `water_heater.turn_off`:
```
alias: Turn on the kettle
sequence:
  - service: water_heater.turn_on
    entity_id: water_heater.skykettle_rk_g211
mode: single
```

Логичнее было бы в первую очередь использовать их, а не переключение режимов.
