### ISSUE TITLE
Текущая температура чайника

### ISSUE THREAD

**Issue by ClusterM** [dmitry-k/yandex_smart_home#364]
Я опять со своим чайником :) Почему-то в УДЯ не отображается его текущая температура.

Свойство `current_temperature` у `water_heater` официально документировано:  https://developers.home-assistant.io/docs/core/entity/water-heater

![image](https://user-images.githubusercontent.com/4236181/155098713-8f9438a4-80a3-403f-b62f-ed7610b0d83f.png)

В УДЯ показывается и настраивается только `target_temperature`.

![image](https://user-images.githubusercontent.com/4236181/155099114-3eba0fcb-0044-4774-b474-a0d8f3414ea5.png)

А должно быть вот так:

![image](https://user-images.githubusercontent.com/4236181/155099728-bb4b953d-4a95-4317-9e3a-3675efb73aec.png)

Я понимаю, что проблема легко решается несколькими строками в конфиге:
```
entity_config:
  water_heater.skykettle_rk_g211:
    properties:
      - type: temperature
        attribute: current_temperature
```
Но это всё-таки похоже на баг.
