### ISSUE TITLE
[entity_config] is an invalid option for [yandex_smart_home]

### ISSUE THREAD

**Issue by lustyffh** [dmitry-k/yandex_smart_home#43]
homeassistant : 0.101.3
yandex_smart_home самый последний через git pull

`2019-11-12 11:51:32 ERROR (MainThread) [homeassistant.components.hassio] Invalid config for [yandex_smart_ho                               me]: [entity_config] is an invalid option for [yandex_smart_home]. Check: yandex_smart_home->yandex_smart_ho                               me->filter->entity_config. (See /config/configuration.yaml, line 66). Please check the docs at https://home-                               assistant.io/integrations/yandex_smart_home/`

конфиг:

```
yandex_smart_home:
  filter:
    include_domains:
      - switch
      - light
    exclude_entities:
      - switch.rfbridge_0
      - switch.rfbridge_1
      - switch.rfbridge_2
      - switch.rfbridge_3
      - switch.rfbridge_4
      - switch.rfbridge_5
      - switch.rfbridge_6
      - switch.rfbridge_7
      - switch.fan_small
  entity_config:
      switch.sonoff:
        name: свет возле окна
        room: спальня
```
