### ISSUE TITLE
Возможность проигрывать на колонке контент через media_player

### ISSUE THREAD

**Issue by tjunussov** [dmitry-k/yandex_smart_home#52]
Ура, наконец то можно выводить звуки,голос,музыку на Yandex Station колонку,

Взято отсюда [https://github.com/AlexxIT/YandexStation/](https://github.com/AlexxIT/YandexStation/)

Пример настройки:
```
script:
  yandex_tts:
    alias: TTS на Яндекс.Станции
    sequence:
      - service: tts.yandex_station_say
        data_template:
          entity_id: media_player.yandex_station_12345678901234567890
          message: Температура в комнате {{ states("sensor.temperature_hall")|round }} градуса.

  yandex_play_album:
    alias: Включить Би-2 на Станции
    sequence:
    - service: media_player.play_media
      data:
        entity_id: media_player.yandex_station_12345678901234567890
        media_content_id: 60062    # ID альбома в Яндекс.Музыка
        media_content_type: album  # album, track or playlist
```
