### ISSUE TITLE
Не работает регулировка света template: lights

### ISSUE THREAD

**Issue by strpc** [dmitry-k/yandex_smart_home#563]
привет! спасибо вам за ваши труды!

имею такой темплейт для управления яркостью света(чтобы отсечь значения очень темно и очень ярко):
```yaml

    - platform: template
      lights:
        dimmer_kitchen_tmpl:
          friendly_name: "Свет кухня"
          value_template: "ON"
          turn_on:
            action: light.turn_on
            data:
              entity_id: light.dimmer_kitchen
              state: "ON"
          turn_off:
            action: light.turn_off
            data:
              entity_id: light.dimmer_kitchen
              state: "OFF"
          level_template: >-
            {{ 80 - (state_attr('light.dimmer_kitchen', 'brightness') | int(1) * (160 - 80) / 100) | int }}
          set_level:
            action: light.turn_on
            data_template:
              entity_id: light.dimmer_kitchen
              brightness: "{{ (brightness | int(1) * (160 - 80) / 254) + 80 | int }}"
```

**словил такой баг:**

"Алиса, сделай свет на кухне ярче" - делает, все ок.  
"Алиса, сделай свет меньше яркость света на кухне"  - ой, что-то пошло не так.

в сентри прилетает вот такое:
```
homeassistant.helpers.script.svet_kukhnia
Свет кухня: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['state']

INTERNAL_ERROR: Failed to execute action for instance brightness (devices.capabilities.range) of light.dimmer_kitchen_tmpl: MultipleInvalid([Invalid('extra keys not allowed')])
```

из логов:
```
Регистратор: custom_components.yandex_smart_home.smart_home
Источник: custom_components/yandex_smart_home/smart_home.py:151

INTERNAL_ERROR: Failed to execute action for instance brightness (devices.capabilities.range) of light.dimmer_kitchen_tmpl: MultipleInvalid([Invalid('extra keys not allowed')])
INTERNAL_ERROR: Failed to execute action for instance on (devices.capabilities.on_off) of light.dimmer_kitchen_tmpl: MultipleInvalid([Invalid('extra keys not allowed')])
```

если нужно еще что-то прислать, буду рад помочь.  

спасибо!
