### ISSUE TITLE
Режимы в посудомойке Bosch

### ISSUE THREAD

**Issue by AKuHAK** [dmitry-k/yandex_smart_home#565]
В посудомойке не получается добавить режимы. В HA они реализованы через switch, возможно что-то делаю не так?

Также второй вопрос, при попытке включения с открытой дверью нет предупреждения об этом. При этом в приложении правильно отображается, когда дверь открыта, а когда закрыта. Я так понимаю при открытой двери должна возвращаться ошибка _DOOR_OPEN_, а возвращается _INTERNAL_ERROR_.
![image](https://github.com/user-attachments/assets/618efaa8-a57d-4b7f-919e-fd7a34195bae)

```yaml
yandex_smart_home:
  entity_config:
    switch.posudomoechnaia_mashina_program_intensiv70:
      name: Посудомойка
      room: Кухня
      type: devices.types.dishwasher
      turn_on:
        service: switch.turn_on
        entity_id: switch.posudomoechnaia_mashina_program_intensiv70
      turn_off:
        service: switch.turn_off
        entity_id: switch.posudomoechnaia_mashina_program_intensiv70
      properties:
        - type: open
          entity: binary_sensor.posudomoechnaia_mashina_door
      custom_toggles:
        controls_locked: # блокировка управления
          state_entity_id: switch.posudomoechnaia_mashina_childlock
          turn_on:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_childlock
          turn_off:
            service: switch.turn_off
            entity_id: switch.posudomoechnaia_mashina_childlock
      modes:
        dishwashing:
          auto:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_auto2
          eco:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_eco50
          express:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_kurz60
          glass:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_machinecare
          intensive:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_intensiv70
          pre_rinse:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_prerinse
          quiet:
            service: switch.turn_on
            entity_id: switch.posudomoechnaia_mashina_program_nightwash
```

**Comment by dext0r** [comment]
Важно: ответ применим к бета версии (https://github.com/dext0r/yandex_smart_home/releases/tag/v1.0.0b1)

> В посудомойке не получается добавить режимы. В HA они реализованы через switch, возможно что-то делаю не так?

Нужно:
1. Настроить связку режимов между УДЯ и HA
2. Релизовать вызов действия по шаблону ([пример](https://docs.yaha-cloud.ru/v1.0.x/advanced/capabilities/mode/#example-coffee-machine))

```yaml
yandex_smart_home:
  entity_config:
    switch.posudomoechnaia_mashina_program_intensiv70:
      modes:
        dishwashing:
          auto: auto2
          eco: eco50
          express: kurz60
          glass: machinecare
          intensive: intensiv70
          pre_rinse: prerinse
          quiet: nightwash
      custom_modes:
        dishwashing:
          set_mode:
            action: switch.turn_on
            target:
              entity_id: switch.posudomoechnaia_mashina_program_{{ mode }}
```

> Также второй вопрос, при попытке включения с открытой дверью нет предупреждения об этом. При этом в приложении правильно отображается, когда дверь открыта, а когда закрыта. Я так понимаю при открытой двери должна возвращаться ошибка DOOR_OPEN, а возвращается INTERNAL_ERROR.

Нужно настроить возврат кода ошибки: https://docs.yaha-cloud.ru/v1.0.x/advanced/error-codes/

```yaml
yandex_smart_home:
  entity_config:
    switch.posudomoechnaia_mashina_program_intensiv70:
      error_code_template: |
        {% if capability.type == 'devices.capabilities.on_off' and capability.state.instance == 'on' and capability.state.value %}
          {% if is_state('binary_sensor.posudomoechnaia_mashina_door', 'on') %}  
            DOOR_OPEN
          {% endif %}
        {% endif %}
```
