### ISSUE TITLE
Для zigbee розетки не привязываются датчики и переключатели в приложении Яндекса

### ISSUE THREAD

**Issue by MiroYar** [dmitry-k/yandex_smart_home#575]
В приложении Яндекса не отображаются датчики и родительский контроль для розетки.
```
yandex_smart_home:
  entity_config:
    switch.socket_zigbee_01_socket_1:
      name: Ночник
      room: Детская
      type: devices.types.light.lamp
      properties:
        - type: power
          entity: sensor.socket_zigbee_01_power
        - type: voltage
          entity: sensor.socket_zigbee_01_voltage
        - type: amperage
          entity: sensor.socket_zigbee_01_current
      custom_toggles:
        controls_locked:
          state_entity_id: switch.socket_zigbee_01_child_lock
          turn_on:
            service: switch.turn_on
            entity_id: switch.socket_zigbee_01_child_lock
          turn_off:
            service: switch.turn_off
            entity_id: switch.socket_zigbee_01_child_lock
```
