### ISSUE TITLE
Неверный порядок режимов

### ISSUE THREAD

**Issue by dext0r** [dmitry-k/yandex_smart_home#585]
```yaml
climate.bedroom_tion_4s_breezer:
  type: ventilation
  modes:
    fan_speed:
      min: '1'
      low: '2'
      medium: '3'
```
приводит к:

![Image](https://github.com/user-attachments/assets/cfb53634-fc1a-466a-94bd-d5099d334be3)
<img src="https://github.com/user-attachments/assets/bb50a7d3-42de-46ad-bbd9-be49e89acc06" width="400" />

Нужно использовать тот порядок режимов, который задан в конфигурации пользователя или в `_modes_map_default` (переделать на OrderedDict)
