### ISSUE TITLE
Как поменять тип кондиционера и включать его всегда на охладение

### ISSUE THREAD

**Issue by from777** [dmitry-k/yandex_smart_home#591]
завожу кондей через knx в алисе он виделся как термостат, удалил кондей из Алисы попробовал прописать такой конфиг

```
yandex_smart_home:
  entity_config:
    climate.konditsioner_spalnia:
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.konditsioner_spalnia
        data:
          hvac_mode: cool
```

и он совсем перестал пробрасываться алису, даже кода конфиг удалил не пробрасывается, хотя раньше мог
В Home Assistant кондей это climate.konditsioner_spalnia

**Comment by dronix27** [comment]
> даже кода конфиг удалил не пробрасывается

А в фильтре для проброса он выбран? То, что у вас написано в _entity_config_ - это не фильтр, а только параметры данного устройства.

**Comment by dext0r** [comment]
Нужно прописть тип `thermostat.ac` (https://docs.yaha-cloud.ru/v1.0.x/config/entity/#type), удалить устройство из УДЯ, и обновить список устройств вручную.

Не забудьте, что `climate.konditsioner_spalnia` должен быть в списке устройств для передачи.

**Comment by from777** [comment]
@dext0r 

конфиг такой должен быть ?

```
yandex_smart_home:
  entity_config:
    climate.konditsioner_spalnia:
      name: Кондиционер спальня
      type: thermostat.ac
      turn_on:
        action: climate.set_hvac_mode
        entity_id: climate.konditsioner_spalnia
        data:
          hvac_mode: cool
```
 то есть задача чтобы в Алисе он виделся как кондей и при включении через алису всегда выбирал режим охлаждения



> удалить устройство из УДЯ, и обновить список устройств вручную

то есть я должен удалить кондей из приложения Алиса на смартфоне ?
а в HA мне надо его удалять в интеграции перед перезагрузкой когда я пропишу выше написанный конфиг в yaml ?




> А в фильтре для проброса он выбран?

что такое фильтр для проброса ?

**Comment by dronix27** [comment]
> что такое фильтр для проброса ?

Список устройств для передачи. Либо через yaml, либо через интерфейс в настройках интеграции. Как вы обычно пробрасываете объекты из ХА в УДЯ

**Comment by from777** [comment]
> Либо через yaml, либо через интерфейс

почему либо то либо другое, я для одного светильника из HA добавил его сначала в веб итерфейсе интеграции yandex smart home, а потом в конфиге дополнил 

```
yandex_smart_home:
  entity_config:
    light.dush_lampochki_templ:
      slow: true
```
и все работает, что не так с кондеем я честно говоря уже запутался, какой алгоритм добавления и что писать в конфиге

**Comment by dronix27** [comment]
> entity_config

Это не проброс. Это параметры. А само устройство вы как добавили? И вообще, такие вопросы лучше уже в чате задавайте.

**Comment by from777** [comment]
> > entity_config
> 
> Это не проброс. Это параметры. А само устройство вы как добавили? И вообще, такие вопросы лучше уже в чате задавайте.

так я же написал все я добавил кондей через веб интерфейс интеграции

![Image](https://github.com/user-attachments/assets/d3558d0a-dd01-4038-900b-713b81ffa6f8)

и вопрос сейчас по конфигу yaml что я написал последний, у меня он верный или есть ошибки ?

**Comment by from777** [comment]
вобщем решил, в документации неправильный конфиг
вот так правильно

```
yandex_smart_home:
  entity_config:
    climate.konditsioner_spalnia:
      name: Кондиционер спальня
      type: thermostat.ac
      turn_on:
        action: climate.set_hvac_mode
        target:
          entity_id: climate.konditsioner_spalnia
        data:
          hvac_mode: cool
```
плюс надо делать обновление устройств в ручную в приложении Алисы иначе не подхватывает
сейчас кондей выглядит как кондей в алисе и всегда включается на охлаждение
