### ISSUE TITLE
Выбор из диапазона - Яркость

### ISSUE THREAD

**Issue by de-andrei** [dmitry-k/yandex_smart_home#599]
Прописываю так. Но в удя яркость отображается в виде нерегулируемого ползунка (от голоса управляется), а должна как "+" и "-".  Температура отображается и управляется корректно.

![Image](https://github.com/user-attachments/assets/834f7fff-a5cd-4c08-ab34-bf05680e6759)

 ```  
 light.zal:
      custom_ranges:
        brightness:
          set_value:
            action: light.turn_on
            entity_id: light.zal
          increase_value:
            action: script.unknown_2
          decrease_value:
            action: script.unknown_3
          range:
            min: 0
            max: 4
            precision: 1
        temperature:
          set_value:
            action: light.turn_on
            entity_id: light.zal
          increase_value:
            action: button.press
            entity_id: button.svet_zal_kholodnyi_svet
          decrease_value:
            action: button.press
            entity_id: button.svet_zal_teplyi_svet
          range:
            min: 0
            max: 2
            precision: 1
```
