### ISSUE TITLE
Не поддерживается вентилятор

### ISSUE THREAD

**Issue by trx900** [dmitry-k/yandex_smart_home#65]
Вентилятор Xiaomi zhimi.fan.v3 в первых ранних версиях компонента поддерживался, далее с вводом регулировки скорости частично стал поддерживаться, сейчас и вовсе не виден\не пробрасывается в yandex
Посмотрите пожалуйста.
![image](https://user-images.githubusercontent.com/46130509/79418405-c272eb80-7fde-11ea-804d-b134562af5a3.png)

**Comment by disinvis** [comment]
Напишите конфигурацию yandex_smart_home в НА.
Можно явно type прописать. Правда не знаю какой. Можно попробовать:
type: devices.types.thermosta или devices.types.purifier или devices.types.other.
Судя по докам https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/device-types-docpage/ нужно выбирать термостат.
Кстати, можно дополнительные датчики температуры, влажности и заряда батареи пробросить, если не появляются сами или используется тип other:
```
properties:
       - type: temperature
          attribute: temperature
       - type: humidity
          attribute: humidity
        - type: battery_level
          attribute: battery
```
У меня такого устройства нет, так что сложно проверить. Можно ещё логи диалога и в модуля в НА посмотреть.
