### ISSUE TITLE
Sonos volume

### ISSUE THREAD

**Issue by InsaneGriever** [dmitry-k/yandex_smart_home#66]
Невозможно задать громкость числом, хотя в самом HA параметр volume_level у media_player.sonos присутствует, как и у телевизора LG. В ТВ работает.
Отличие в стейте ТВ- on/off, а в Sonos- playing/paused.
Если создать плеер с помощью компонента universal, тогда управление громкостью Sonos работает, но только при включенном телевизоре. С другими children устройствами управление становится недоступно.
```
  platform: universal
  name: Test Universal
  children:
    - media_player.lg_tv
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.sonos
        volume_level: '{{ volume_level }}'
  attributes:
    volume_level: media_player.sonos|volume_level
```
